export const enum OrderStatus {
  STARTED = 'STARTED',
  ORDERED = 'ORDERED',
  WAITING = 'WAITING',
  DELIVERED = 'DELIVERED',
  CANCELED_BY_RESTORANT = 'CANCELED_BY_RESTORANT',
  CANCELED_BY_USER = 'CANCELED_BY_USER'
}
