package et.com.delivereth.domain.enumeration;

/**
 * The OrderStatus enumeration.
 */
public enum OrderStatus {
    STARTED, ORDERED, ACCEPTED_BY_RESTAURANT, READY_FOR_DELIVERY, ACCEPTED_BY_DRIVER, DELIVERED, CANCELED_BY_RESTAURANT, CANCELED_BY_USER, EXPIRED_AND_CANCELED_BY_SYSTEM, DELIVERED_AND_REMOVED, CANCELED_BY_RESTAURANT_AND_REMOVED
}
